export const fakeCategory=[
    {
        id:1,
        img:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS2PD2yAr4Tt4TG62BatFqSltJmYLO1_DFUqA&usqp=CAU',
        lang:'HTML'
    },
    {
        id:2,
        img:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRlX2_FbK6iXeg1k9hOM5xFudfNJhAUQhIXrw&usqp=CAU',
        lang:'CSS'
    },
    {
        id:3,
        img:'https://img1.freepng.fr/20180720/bv/kisspng-javascript-logo-html-clip-art-javascript-logo-5b5188b13c2314.0304322315320700652463.jpg',
        lang:'JAVASCRIPT'
    },
    {
        id:4,
        img:'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Bootstrap_logo.svg/1280px-Bootstrap_logo.svg.png',
        lang:'BOOTSTRAP'
    },{
        id:5,
        img:'https://assets.stickpng.com/images/5848152fcef1014c0b5e4967.png',
        lang:'PHYTON'
    },
    {
        id:6,
        img:'https://i.pinimg.com/originals/2d/3a/7d/2d3a7d7d1ad7adeded994de246f60c43.png',
        lang:'PHP'
    },
    {
        id:7,
        img:'https://w7.pngwing.com/pngs/1007/564/png-transparent-java-script-logo-javascript-web-development-logo-script-text-computer-programming-internet.png',
        lang:'JAVA'
    },
    {
        id:8,
        img:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR4reE6E_K60oJC1XpZe-ZC3EM2vkTl8wdFoA&usqp=CAU',
        lang:'C++'
    },
    {
        id:9,
        img:'https://upload.wikimedia.org/wikipedia/commons/4/4f/Csharp_Logo.png',
        lang:'C#'
    }
]